import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
    ],

    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
            colors: {
              "surface-container-low": "#131316",
              "on-tertiary-container": "#0e000a",
              "outline-variant": "#48474b",
              "tertiary-fixed": "#ff87db",
              "primary-fixed-dim": "#00deec",
              "surface-dim": "#0e0e11",
              "surface-container": "#19191d",
              "on-error": "#490013",
              "on-surface-variant": "#acaaae",
              "inverse-surface": "#fcf8fd",
              error: "#ff6e84",
              "primary-container": "#00eefc",
              "on-error-container": "#ffb2b9",
              "on-primary-fixed": "#003f43",
              tertiary: "#ff5dd7",
              secondary: "#ac89ff",
              "on-secondary-fixed": "#41009a",
              "error-container": "#a70138",
              outline: "#767579",
              "secondary-container": "#7000ff",
              "on-primary": "#005d63",
              "primary-dim": "#00deec",
              surface: "#0e0e11",
              "on-primary-container": "#005359",
              "surface-bright": "#2c2c30",
              "inverse-on-surface": "#555458",
              "secondary-fixed-dim": "#ceb9ff",
              "on-background": "#f0edf1",
              primary: "#8ff5ff",
              "surface-variant": "#25252a",
              "inverse-primary": "#006a71",
              "tertiary-container": "#fe00d5",
              "primary-fixed": "#00eefc",
              "on-secondary-fixed-variant": "#6300e2",
              "secondary-dim": "#874cff",
              "on-primary-fixed-variant": "#005e64",
              "secondary-fixed": "#dac9ff",
              "on-secondary": "#290067",
              "on-tertiary-fixed": "#34002a",
              "on-secondary-container": "#f8f1ff",
              "on-surface": "#f0edf1",
              background: "#0e0e11",
              "tertiary-fixed-dim": "#ff6ad8",
              "surface-container-lowest": "#000000",
              "surface-tint": "#8ff5ff",
              "error-dim": "#d73357",
              "surface-container-high": "#1f1f23",
              "tertiary-dim": "#ff5dd7",
              "surface-container-highest": "#25252a",
              "on-tertiary": "#430036",
              "on-tertiary-fixed-variant": "#6f005c",
            },
            fontFamily: {
              headline: ["Space Grotesk"],
              body: ["Manrope"],
              label: ["Inter"],
            },
            borderRadius: {
              DEFAULT: "0.125rem",
              lg: "0.25rem",
              xl: "0.5rem",
              full: "0.75rem",
            },
        },
    },

    plugins: [forms],
};